---
title: "Untitled"
author: '26966767'
date: "12/11/2016"
output: pdf_document
---


# Import 2012 and 2016 election data that Tony McGovern has compiled by scraping through townhall.com home page. (Official result is not yet available in county level as of December 11, 2016)

```{r}
# import necessary package
library(RCurl)

# Get URL 
x <- getURL("https://raw.githubusercontent.com/tonmcg/County_Level_Election_Results_12-16/master/US_County_Level_Presidential_Results_12-16.csv")

# Read it in CSV
y <- read.csv(text = x)

# See the summary
summary(y)
```

# Create a couple of variables to use in the analysis

```{r}
# The growth in the vote count 
y$puregrowth <- y$votes_gop_2016 - y$votes_gop_2012

# The growth in the voting share
y$pergrowth <- y$per_gop_2016 - y$per_gop_2012

# THe growth in the winning (losing) margin
y$margingrowth <- -(y$per_point_diff_2016 - y$per_point_diff_2012)

# Visualize the data
hist(y$margingrowth)
summary(y$margingrowth)

# ALaska was not available yet, so there are 29 NAs.

# Write the arranged data into CSV file
write.csv(y, file = "election.csv")

```
