---
title: "Untitled"
author: '26966767'
date: "12/11/2016"
output: html_document
---


# Visualization 

```{r}

# Import the packages necessary for visualization 

require(ggplot2)
require(gridExtra)

```

# Covariates and Trump margin - Romney margin; Note that aside from education, not many variables are correlated with the increase in GOP margin. 

```{r}

# Hispanic * Trump

ggplot(swing2, aes(x = hisp_r, y = margingrowth))  + 
  ggtitle("Hispanic and Trump margin - Romney margin") + 
  geom_point(aes(colour = white_r) )+ 
  scale_color_continuous(name="White", low = 'pink', high = "red")  

# Just for Florida

ggplot(florida2, aes(x = hisp_r, y = margingrowth))  + 
  ggtitle("Florida: Hispanic and Trump margin - Romney margin") + 
  geom_point(aes(colour = white_r) )+ 
  scale_color_continuous(name="White", low = 'pink', high = "red")  

# Median Income * Trump 

ggplot(swing2, aes(x = MedianIncome, y = margingrowth))  + 
  ggtitle("Median Income and Trump margin - Romney margin") + 
  geom_point(aes(colour = Management)) + 
  scale_color_continuous(name="Management Occupation", low = 'pink', high = "red")  

# Just for Virginia
ggplot(virginia2, aes(x = MedianIncome, y = margingrowth))  + 
  ggtitle("Virginia: Median Income and Trump margin - Romney margin") + 
  geom_point(aes(colour = Management)) + 
  scale_color_continuous(name="Management Occupation", low = 'pink', high = "red")  

# Education * Trump
ggplot(swing2, aes(x = univ_r, y = margingrowth))  + 
  ggtitle("Bachelor degree holder's share and Trump's margin compared to Romney's") + 
  geom_point(aes(colour = MedianIncome)) + 
  scale_color_continuous(name="High School", low = 'pink', high = "red") 

# Just for North Carolina
ggplot(nc2, aes(x = univ_r, y = margingrowth))  + 
  ggtitle("NC: Bachelor degree holder's share and Trump's margin compared to Romney's") + 
  geom_point(aes(colour = MedianIncome)) + 
  scale_color_continuous(name="High School", low = 'pink', high = "red") 

# Elderly * Trump 

ggplot(swing2, aes(x = elder, y = margingrowth))  + 
  ggtitle("Elderly and Trump's margin compared to Romney's") + 
  geom_point(aes(colour = youth)) + 
  scale_color_continuous(name="youth", low = 'pink', high = "red")  

# Just for New Hampshire

ggplot(nh2, aes(x = elder, y = margingrowth))  + 
  ggtitle("Elderly and Trump's margin compared to Romney's") + 
  geom_point(aes(colour = youth)) + 
  scale_color_continuous(name="youth", low = 'pink', high = "red")  


# Manufacture * Trump

ggplot(swing2, aes(x = manufacture_r, y = margingrowth))  + 
  ggtitle("Manufacture and Trump's margin compared to Romney's") + 
  geom_point(aes(colour = agriculture_r)) + 
  scale_color_continuous(name="Agriculture", low = 'pink', high = "red")  

# Just for Michigan

ggplot(michigan2, aes(x = manufacture_r, y = margingrowth))  + 
  ggtitle("Michigan: Manufacture and Trump's margin compared to Romney's") + 
  geom_point(aes(colour = agriculture_r)) + 
  scale_color_continuous(name="Agriculture", low = 'pink', high = "red")  

ls(total2)

# Unemployment rate * Trump

ggplot(swing2, aes(x = unemp_r, y = margingrowth))  + 
  ggtitle("Unemployment rate and Trump's margin compared to Romney's") + 
  geom_point(aes(colour = active_r)) + 
  scale_color_continuous(name="Activity rate", low = 'pink', high = "red")  

# Just for Ohio

ggplot(ohio2, aes(x = unemp_r, y = margingrowth))  + 
  ggtitle("Ohio: Unemployment rate and Trump's margin compared to Romney's") + 
  geom_point(aes(colour = active_r)) + 
  scale_color_continuous(name="Activity rate", low = 'pink', high = "red")  

```

# Main point: Population growth and increasing margin

```{r}

# Population growth * Trump vote
ggplot(swing2, aes(x = pop_growth, y = margingrowth))  + 
  ggtitle("Population growth and Trump's margin compared to Romney's") + 
  geom_point(aes(colour = move_in)) + 
  scale_color_continuous(name="Recent move in", low = 'pink', high = "red")  +
  geom_smooth(method = "lm", se = FALSE)

# Just for Virginia

ggplot(virginia2, aes(x = pop_growth, y = margingrowth))  + 
  ggtitle("Virginia: Population growth and Trump's margin compared to Romney's") + 
  geom_point(aes(colour = move_in)) + 
  scale_color_continuous(name="Recent move in", low = 'pink', high = "red")   +
  geom_smooth(method = "lm", se = FALSE)

# Income growth * Trump vote

ggplot(swing2, aes(x = income_growth, y = margingrowth))  + 
  ggtitle("Median Income growth and Trump's margin compared to Romney's") + 
  geom_point(aes(colour = active_r)) + 
  scale_color_continuous(name="Activity rate", low = 'pink', high = "red")

# Just for Virginia 

ggplot(virginia2, aes(x = income_growth, y = margingrowth))  + 
  ggtitle("Virginia: Median Income growth and Trump's margin compared to Romney's") + 
  geom_point(aes(colour = active_r)) + 
  scale_color_continuous(name="Activity rate", low = 'pink', high = "red")  


```

# Use dependent variabales other than margins

```{r}

# Voting share 
ggplot(swing2, aes(x = pop_growth, y = pergrowth))  + 
  ggtitle("Population growth and Trump's share compared to Romney's") + 
  geom_point(aes(colour = move_in)) + 
  scale_color_continuous(name="Recent move in", low = 'pink', high = "red")  +
  geom_smooth(method = "lm", se = FALSE)

# Vote count 
ggplot(swing2, aes(x = pop_growth, y = margingrowth))  + 
  ggtitle("Population growth and Trump's margin compared to Romney's") + 
  geom_point(aes(colour = move_in)) + 
  scale_color_continuous(name="Recent move in", low = 'pink', high = "red")  +
  geom_smooth(method = "lm", se = FALSE)

```

# Go deeper than "population decrease" 

```{r}
ggplot(swing2, aes(x = homegrown, y = margingrowth))  + 
  ggtitle("Population born in the state and Trump's margin compared to Romney's") + 
  geom_point(aes(colour = move_in)) + 
  scale_color_continuous(name="Recent move in", low = 'pink', high = "red")  +
  geom_smooth(method = "lm", se = FALSE)

ggplot(swing2, aes(x = same_house, y = margingrowth))  + 
  ggtitle("Population living in the Same house 1 year ago and Trump's margin compared to Romney's") + 
  geom_point(aes(colour = move_out)) + 
  scale_color_continuous(name="Recent move out", low = 'pink', high = "red")  

ggplot(swing2, aes(x = move_in, y = margingrowth))  + 
  ggtitle("Population recently moved in and Trump's margin compared to Romney's") + 
  geom_point(aes(colour = move_out)) + 
  scale_color_continuous(name="Recent move out", low = 'pink', high = "red")  

```
