---
title: "Untitled"
author: '26966767'
date: "12/11/2016"
output: html_document
---


# Multivaraiate regression

```{r}
library(stargazer)

# Full model 

lm0 <- lm(margingrowth~pop_growth+income_growth+homegrown+same_house+move_in+move_out+
            univ_r+highschool_r+white_r+hisp_r+black_r+unemp_r+active_r+elder+youth+manufacture_r+agriculture_r+management_r+MedianIncome+MedianAge+homeowner_r+Foodstamp,
          data=swing2)
summary(lm0)

# Omit some variables that are closely related to each other 

lm1 <- lm(margingrowth~pop_growth+income_growth+
            univ_r+hisp_r+black_r+unemp_r+active_r+elder+youth+manufacture_r+agriculture_r+MedianIncome+MedianAge+homeowner_r+Foodstamp,
          data=swing2)
summary(lm1)

lm2 <- lm(margingrowth~pop_growth+income_growth+homegrown+move_in+
            univ_r+hisp_r+black_r+active_r+elder+manufacture_r+agriculture_r+MedianIncome+MedianAge+homeowner_r+Foodstamp,
          data=swing2)
summary(lm2)

# USA as a whole, not Swing states 

lm3 <- lm(margingrowth~pop_growth+income_growth+
            univ_r+hisp_r+black_r+unemp_r+active_r+elder+youth+manufacture_r+agriculture_r+MedianIncome+MedianAge+homeowner_r+Foodstamp,
          data=total2)
summary(lm3)

```

# Create a table using "stargazer" package

```{r}
stargazer(lm0, lm1, lm2, lm3, type = "text", title="Regression Results")
```

